//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AU_Tasks_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int DEPT_ID { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
