//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AU_Tasks_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_ATTENDENCE
    {
        public long ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.TimeSpan> CHECK_IN_TIME { get; set; }
        public Nullable<System.TimeSpan> CHECK_OUT_TIME { get; set; }
        public Nullable<System.DateTime> CHECK_IN_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string IP_ADDRESS { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
