//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AU_Tasks_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_RELEASE_NOTE
    {
        public long NOTE_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public string RELEASE_NOTE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual AU_TASK AU_TASK { get; set; }
    }
}
