//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AU_Tasks_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.AU_TASK = new HashSet<AU_TASK>();
            this.STAFF_ATTENDENCE = new HashSet<STAFF_ATTENDENCE>();
        }
    
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<int> USER_DEPARTMENT { get; set; }
        public string USER_ROLE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    
        public virtual ICollection<AU_TASK> AU_TASK { get; set; }
        public virtual ICollection<STAFF_ATTENDENCE> STAFF_ATTENDENCE { get; set; }
    }
}
